version: "3.9"
services:
  app:
    build: .
    env_file: .env
    volumes:
      - .:/app
      - data:/data
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: nouchka/sqlite3
    volumes:
      - data:/data
    command: sh -c "sqlite3 /data/sqlite.db < /db/schema.sql"
volumes:
  data:

