name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-dev
      - name: Lint
        run: |
          pip install ruff
          ruff check .
      - name: Tests
        run: |
          pip install pytest pytest-asyncio
          pytest -q
      - name: Docker build
        run: |
          docker build -t dukeo .

